/*
Project: Lab #1 [BULCOW Game]
Name: Created by Andy E. Wold and Miranda Motter
Date: Wed, 18 May 2016
Description: Number guessing game 
Instructor: Bro. Daniel Masterson, Jr.
Section: CS 176 -- Windows Desktop Development [C#]
*/

using System;
using static System.Console;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Lab_01_BULCOW
{
    class Program
    {
        static string DetermineBullCow(string sN, string uG, int cB, int cC)
        {
            if (uG != "00000")
            {
                // Determine the number of Bulls
                for (int i = 0; i < 5; i++)
                {
                    if (sN[i] == uG[i])
                    {
                        cB++;
                    }
                }
                Write("Bulls: " + cB);

                // Determine the number of Cows
                for (int i = 0; i < 5; i++)
                {
                    if (sN.Contains(uG[i]))
                    {
                        cC++;
                    }
                }
                cC = cC - cB;
                WriteLine("  Cows: " + cC);
            }
            cB = 0;
            cC = 0;

            return sN;
        }
            
        static void Main(string[] args)
        {
            PlayAgain:
            Clear();
            Random rnd = new Random();

            // Initialize victory number
            int checkNum = 0;
            int guessCount = 0;
            string solutionNum = "";
            string exitQuit = "";

            // Generate a 5-digit number with unique numbers
            while (solutionNum.Length < 5)
            {
                TryAgain:

                // Reassign number to random int
                checkNum = rnd.Next(1, 9);

                // Check number for duplicates
                if (solutionNum.Contains(Convert.ToString(checkNum)))
                {
                    goto TryAgain;
                }
                solutionNum = solutionNum + Convert.ToString(checkNum);

            }

            //Test - keep for pass-off, would remove for actual game
            WriteLine("The number generated by the computer is: " + solutionNum);
            WriteLine();

            // Display rules to player
            WriteLine("You will need to guess the 5-digit number I am thinking of. ");
            WriteLine();
            WriteLine("All 5 digits must be unique, and be between 1-9.");
            WriteLine();
            WriteLine("You will get one Bull for each correct digit in the correct place.");
            WriteLine("You will get one Cow for each correct digit that is NOT in the correct place.");
            WriteLine();

            // Initialize game variables
            string userGuess = "";
            int countBull = 0;
            int countCows = 0;

            // Loop through until user guesses the correct number
            // Once the number is correctly guessed, it will exit the WHILE loop
            while (solutionNum != userGuess)
            {
                InvalidGuess:

                // Get guess from user
                Write("Please enter your guess or \"00000\" to quit: ");
                userGuess = ReadLine();

                // Check if the user wants to quit
                if (userGuess == "00000")
                {
                    exitQuit = "Y";
                    guessCount = guessCount--;
                    break;
                }
                else if (userGuess.Length != 5)
                {
                    WriteLine("Guess contains wrong number of digits. Please try again.");
                    goto InvalidGuess;
                }

                // Confirm that guessed number digits are from 1 to 9
                string validNumbers = "123456789";

                for (int i = 0; i < 5; i++)
                {
                    if (validNumbers.Contains(Convert.ToString(userGuess[i])))
                        continue;
                    else
                    {
                        WriteLine("You did not enter numbers between 1 and 9.");
                        goto InvalidGuess;
                    }
                }

                // Check the last digit of the guess against the remaining digits
                for (int i = 0; i < 5; i++)
                {
                    for (int j = 0; j < 5; j++)
                    {
                        if (i != j && userGuess[i] == userGuess[j])
                        {
                            WriteLine("Your guess contains duplicate digits.");
                            goto InvalidGuess;
                        }
                    }
                }

                string results = DetermineBullCow(solutionNum,userGuess,countBull,countCows);
                guessCount++;
            }

            if (exitQuit == "Y")
            {
                // When the user quits
                WriteLine();
                WriteLine("You have quit the game after only " + guessCount + " guesses.");
                WriteLine("You should have guessed " + solutionNum + ", loser.  ;)");
            }
            else
            {
                // When the user's guess matches the computer's number
                WriteLine();
                WriteLine("CONGRATULATIONS!  You guessed my number, " + solutionNum + ", in only " 
                    + guessCount + " guesses!");
            }

            // Ask user if they would like to play again
            WriteLine();
            Write("Would you like to play again? (Y/N) ");
            var replaySelection = ReadKey();
            while (replaySelection.Key != ConsoleKey.Y && replaySelection.Key != ConsoleKey.N) { }
            if (replaySelection.Key == ConsoleKey.Y)
            {
                goto PlayAgain;
            }
        }
    }
}
